ads/urls.py
from django.urls import path

from ads.apps import AdsConfig
from ads.views import (AcceptExchangeProposalView, AdCreateView, AdDeleteView, AdDetailView, AdListView, AdMyListView,
                       AdSearchListView, AdUpdateView, ExchangeProposalCreate, ExchangeProposalDeleteView,
                       ExchangeProposalListView, HomeTemplateView, MyExchangeProposalListView,
                       OffersExchangeProposalListView, RefuseExchangeProposalView)

app_name = AdsConfig.name

urlpatterns = [
    path("", HomeTemplateView.as_view(), name="home"),
    path("ad-create/", AdCreateView.as_view(), name="ad-create"),
    path("ads/", AdListView.as_view(), name="ads-list"),
    path("my_ads/", AdMyListView.as_view(), name="ads-mylist"),
    path("<int:pk>/ad/", AdDetailView.as_view(), name="ad-detail"),
    path("<int:pk>/update/", AdUpdateView.as_view(), name="ad-update"),
    path("<int:pk>/delete/", AdDeleteView.as_view(), name="ad-delete"),
    path("exchange-create/<int:pk>/", ExchangeProposalCreate.as_view(), name="exchange-create"),
    path("exchanges/", ExchangeProposalListView.as_view(), name="exchanges-list"),
    path("my_exchanges/", MyExchangeProposalListView.as_view(), name="my-exchanges-list"),
    path("offers_exchanges/", OffersExchangeProposalListView.as_view(), name="offers-exchanges"),
    path("accept-exchange-proposal/<int:pk>/", AcceptExchangeProposalView.as_view(), name="accept-exchange-proposal"),
    path("refuse-exchange-proposal/<int:pk>/", RefuseExchangeProposalView.as_view(), name="refuse-exchange-proposal"),
    path("delete-exchange-proposal/<int:pk>/", ExchangeProposalDeleteView.as_view(), name="delete-exchange-proposal"),
    path("search/", AdSearchListView.as_view(), name="search-ads"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ads.urls", namespace="ads")),
    path("", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import PersonalAccountDetailView, UserCreateView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="users:login"), name="logout"),
    path("user/<int:pk>/update/", UserUpdateView.as_view(), name="user-update"),
    path("personal-account/<int:pk>/", PersonalAccountDetailView.as_view(), name="personal-account"),
]

users/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    """Модель пользователя."""

    username = None

    email = models.EmailField(unique=True, verbose_name="Email")
    phone = models.CharField(max_length=15, verbose_name="Телефон", blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from ads.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """Форма регистрации пользователя."""

    class Meta:
        model = User
        fields = ("email", "phone", "password1", "password2")

    def __init__(self, *args, **kwargs):
        """Переопределение меток полей."""

        super().__init__(*args, **kwargs)
        self.fields["password1"].label = "Пароль"
        self.fields["password2"].label = "Повторите пароль"

        # Отключение help_text для всех полей.
        for field in self.fields.values():
            field.help_text = None

users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView

from users.forms import UserRegisterForm
from users.models import User


class UserCreateView(CreateView):
    """Регистрация пользователя"""

    model = User
    form_class = UserRegisterForm
    template_name = "user_form.html"
    success_url = reverse_lazy("users:login")


class UserUpdateView(UpdateView):
    """Редактирование пользователя."""

    model = User
    form_class = UserRegisterForm
    template_name = "user_form.html"
    success_url = reverse_lazy("users:personal-account")


class PersonalAccountDetailView(DetailView):
    """Личный кабинет."""

    model = User
    template_name = "personal_account.html"
    context_object_name = "user"

users/templates/login.html
{% extends 'base.html' %}
{% load my_tags %}
{% block title %}Вход{% endblock %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data" action="{% url 'users:login' %}" style="width: 100%" class="mx-auto w-50">
            {% csrf_token %}
            <fieldset>
                <legend class="center">
                    <h3>Вход</h3>
                </legend>
                {{ form.as_p }}
                <button type="submit" class="btn btn-secondary btn-lg">Войти</button>
            </fieldset>
        </form>
</div>
{% endblock %}

users/templates/personal_account.html
{% extends 'base.html' %}
{% load my_tags %}
{% block title %}Личный кабинет{% endblock %}
{% block content %}
<h1 class="mb-5" style="text-align: center;">Личные данные</h1>
<div class="container">
            <p style="font-size: 25px;"><strong>Email:</strong> {{ user.email }}</p>
    {% if user.phone %}
            <p style="font-size: 25px;"><strong>Телефон:</strong> {{ user.phone }}</p>
    {% endif %}
        </div>
        <div class="container-button mt-5">
                <a href="{% url 'users:user-update' user.pk %}"><button type="button" class="btn btn-secondary btn-lg" style="width: 250px;">Редактировать</button></a>
                    </div>
{% endblock %}

users/templates/user_form.html
{% extends 'base.html' %}
{% load my_tags %}
{% block title %}
{% if not user.is_authenticated %}Регистрация{% endif %}
{% if user.is_authenticated %}Редактирование личных данных{% endif %}
{% endblock %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data" action="" style="width: 100%" class="mx-auto w-50">
                        {% csrf_token %}
                        <fieldset>
                <legend class="center">
                    {% if object %}
                    <h3>Редактирование данных</h3>
                    {% else %}
                    <h3>Регистрация</h3>
                    {% endif %}
                </legend>
                {{ form.as_p }}
                            {% if object %}
            <button type="submit" class="btn btn btn-lg">Редактировать</button>
            {% else %}
                    <button type="submit" class="btn btn btn-lg">Зарегистрироваться</button>
            {% endif %}
            </fieldset>
    </form>
</div>
{% endblock %}