ads/urls.py
from django.urls import path

from ads.apps import AdsConfig
from ads.views import (AcceptExchangeProposalView, AdCreateView, AdDeleteView, AdDetailView, AdListView, AdMyListView,
                       AdSearchListView, AdUpdateView, ExchangeProposalCreate, ExchangeProposalDeleteView,
                       ExchangeProposalListView, HomeTemplateView, MyExchangeProposalListView,
                       OffersExchangeProposalListView, RefuseExchangeProposalView)

app_name = AdsConfig.name

urlpatterns = [
    path("", HomeTemplateView.as_view(), name="home"),
    path("ad-create/", AdCreateView.as_view(), name="ad-create"),
    path("ads/", AdListView.as_view(), name="ads-list"),
    path("my_ads/", AdMyListView.as_view(), name="ads-mylist"),
    path("<int:pk>/ad/", AdDetailView.as_view(), name="ad-detail"),
    path("<int:pk>/update/", AdUpdateView.as_view(), name="ad-update"),
    path("<int:pk>/delete/", AdDeleteView.as_view(), name="ad-delete"),
    path("exchange-create/<int:pk>/", ExchangeProposalCreate.as_view(), name="exchange-create"),
    path("exchanges/", ExchangeProposalListView.as_view(), name="exchanges-list"),
    path("my_exchanges/", MyExchangeProposalListView.as_view(), name="my-exchanges-list"),
    path("offers_exchanges/", OffersExchangeProposalListView.as_view(), name="offers-exchanges"),
    path("accept-exchange-proposal/<int:pk>/", AcceptExchangeProposalView.as_view(), name="accept-exchange-proposal"),
    path("refuse-exchange-proposal/<int:pk>/", RefuseExchangeProposalView.as_view(), name="refuse-exchange-proposal"),
    path("delete-exchange-proposal/<int:pk>/", ExchangeProposalDeleteView.as_view(), name="delete-exchange-proposal"),
    path("search/", AdSearchListView.as_view(), name="search-ads"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ads.urls", namespace="ads")),
    path("", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads/models.py
from django.db import models

from users.models import User


class Ad(models.Model):
    """Модель объявления."""

    # выбор состояния товара
    CONDITION_CHOICES = (
        ("новый", "Новый"),
        ("б/у", "Б/у"),
    )
    # выбор категории
    CATEGORY_CHOICES = (
        ("одежда", "Одежда"),
        ("обувь", "Обувь"),
        ("аксессуары", "Аксессуары"),
        ("хобби", "Хобби"),
        ("электроника", "Электроника"),
        ("для дома и дачи", "Для дома и дачи"),
        ("запчасти", "Запчасти"),
        ("товары для детей", "Товары для детей"),
        ("красота и здоровье", "Красота и здоровье"),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Создатель объявления")
    title = models.CharField(max_length=250, verbose_name="Заголовок объявления")
    description = models.TextField(verbose_name="Описание товара")
    image_url = models.ImageField(upload_to="ad_images", verbose_name="Изображение", blank=True, null=True)
    category = models.CharField(max_length=30, verbose_name="Категория товара", choices=CATEGORY_CHOICES)
    condition = models.CharField(max_length=10, verbose_name="Состояние товара", choices=CONDITION_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания объявления")

    class Meta:
        verbose_name = "Объявление"
        verbose_name_plural = "Объявления"

    def __str__(self):
        return self.title


class ExchangeProposal(models.Model):
    """Модель для предложений обмена."""

    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name="Создатель предложения обмена")
    ad_sender = models.ForeignKey(
        Ad, on_delete=models.DO_NOTHING, verbose_name="Что менять", related_name="sender_exchange_proposals"
    )
    ad_receiver = models.ForeignKey(
        Ad, on_delete=models.DO_NOTHING, verbose_name="На что менять", related_name="receiver_exchange_proposals"
    )
    comment = models.TextField(verbose_name="Комментарий")
    status = models.CharField(max_length=15, verbose_name="Статус", default="Ожидает")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания объявления")

    class Meta:
        verbose_name = "Предложение обмена"
        verbose_name_plural = "Предложения обмена"

ads/forms.py
from django import forms

from .mixins import StyleFormMixin
from .models import Ad, ExchangeProposal


class AdForm(StyleFormMixin, forms.ModelForm):
    """Форма для объявления."""

    class Meta:
        model = Ad
        fields = ["title", "description", "image_url", "category", "condition"]
        # widgets = {
        #     'condition': forms.Select(attrs={'class': 'form-control'}),
        # }


class ExchangeProposalForm(StyleFormMixin, forms.ModelForm):
    """Форма для обмена."""

    class Meta:
        model = ExchangeProposal
        fields = [
            "ad_receiver",
            "comment",
        ]

    def __init__(self, *args, **kwargs):

        # Устанавливаем queryset, чтобы выбрать только объявления текущего пользователя
        user = kwargs.pop("user", None)  # Получаем пользователя из kwargs и удаляем его оттуда
        super().__init__(*args, **kwargs)

        if user:
            self.fields["ad_receiver"].queryset = Ad.objects.filter(user=user)
        else:
            self.fields["ad_receiver"].queryset = Ad.objects.none()
        self.fields["comment"].initial = ""

ads/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.postgres.search import SearchQuery, SearchVector
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView
from django.views.generic.detail import SingleObjectMixin

from ads.forms import AdForm, ExchangeProposalForm
from ads.models import Ad, ExchangeProposal


class HomeTemplateView(TemplateView):
    """Главная страница."""

    template_name = "home.html"

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Главная"

        return context


class AdCreateView(LoginRequiredMixin, CreateView):
    """Создание объявления."""

    model = Ad
    form_class = AdForm
    template_name = "ad_form.html"

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Добавление объявления"

        return context

    def form_valid(self, form):
        """Добавляет текущего пользователя, как создателя объявления."""

        ad = form.save(commit=False)
        ad.user = self.request.user
        ad.save()

        return super().form_valid(form)

    def get_success_url(self):
        """Перенаправление на созданное объявление."""

        return reverse("ads:ad-detail", kwargs={"pk": self.object.pk})


class AdListView(ListView):
    """Список объявлений."""

    model = Ad
    template_name = "ads.html"
    context_object_name = "ads"

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Объявления"

        return context

    def get_queryset(self):
        """Возвращает объявления других пользователей."""

        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            queryset = queryset.exclude(user=user)

        return queryset


class AdMyListView(LoginRequiredMixin, ListView):
    """Список моих объявлений."""

    model = Ad
    template_name = "ads.html"
    context_object_name = "ads"

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Мои объявления"

        return context

    def get_queryset(self):
        """Возвращает объявления текущего пользователя."""

        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            queryset = queryset.filter(user=user)
        else:
            queryset = Ad.objects.none()

        return queryset


class AdDetailView(DetailView):
    """Информация об объявлении."""

    model = Ad
    template_name = "ad.html"
    context_object_name = "ad"

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        if Ad.objects.get(id=self.object.id).user == self.request.user:
            my = 'Мое объявление'
        else:
            my = ''
        context["current_page"] = "Объявление"
        context["my"] = my

        return context


class AdUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование объявления."""

    model = Ad
    form_class = AdForm
    template_name = "ad_form.html"
    success_url = reverse_lazy("ads:ads-mylist")

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Редактирование"

        return context


class AdDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление объявления."""

    model = Ad
    template_name = "confirm-delete.html"
    success_url = reverse_lazy("ads:ads-mylist")

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Удаление объявления"

        return context


class ExchangeProposalCreate(LoginRequiredMixin, CreateView):
    """Создание обмена."""

    model = ExchangeProposal
    form_class = ExchangeProposalForm
    template_name = "exchange_proposal_form.html"
    success_url = reverse_lazy("ads:ads-list")

    def get_form_kwargs(self):
        """Передаем текущего пользователя в форму."""

        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})

        return kwargs

    def form_valid(self, form):
        """Автоматически устанавливаем объявление отправителя и делаем владельцем текущего пользователя."""

        user = self.request.user
        ad_id = self.kwargs.get("pk")
        sender_ad = Ad.objects.get(id=ad_id)
        form.instance.ad_sender = sender_ad
        form.instance.owner = user

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        ad_id = self.kwargs.get("pk")
        context["current_page"] = "Предложение обмена"
        context["ad"] = Ad.objects.get(id=ad_id)

        return context


class ExchangeProposalListView(LoginRequiredMixin, ListView):
    """Список обменов."""

    model = ExchangeProposal
    template_name = "exchange_proposals.html"
    context_object_name = "exchanges_ok"

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон и списков состоявшихся и не состоявшихся обменов."""

        context = super().get_context_data(**kwargs)
        user = self.request.user
        users_ads = Ad.objects.filter(user=user)
        context["current_page"] = "Обмены"
        # принятые обмены
        context["exchanges_ok"] = ExchangeProposal.objects.filter(
            Q(ad_sender__in=users_ads) | Q(ad_receiver__in=users_ads), status="Подтвержден"
        )
        # отклоненные обмены
        context["exchanges"] = ExchangeProposal.objects.filter(
            Q(ad_sender__in=users_ads) | Q(ad_receiver__in=users_ads), status="Отклонен"
        )

        return context


class MyExchangeProposalListView(LoginRequiredMixin, ListView):
    """Я предлагаю поменяться."""

    model = ExchangeProposal
    template_name = "exchange_proposals1.html"
    context_object_name = "exchanges"

    def get_queryset(self):
        """Возвращает предложения обмена созданные текущим пользователем."""

        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            queryset = queryset.filter(owner=user, status="Ожидает")
        else:
            queryset = Ad.objects.none()

        return queryset

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Вы предлагаете обмен"

        return context


class OffersExchangeProposalListView(LoginRequiredMixin, ListView):
    """Вам предлагают поменяться."""

    model = ExchangeProposal
    template_name = "exchange_proposals1.html"
    context_object_name = "exchanges"

    def get_queryset(self):
        """Возвращает предложения обмена от других пользователей."""

        queryset = super().get_queryset()
        user = self.request.user
        users_ads = Ad.objects.exclude(user=user)
        queryset = ExchangeProposal.objects.filter(ad_receiver__in=users_ads, status="Ожидает")

        return queryset

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Вам предлагают обмен"

        return context


class AcceptExchangeProposalView(LoginRequiredMixin, SingleObjectMixin, View):
    """Обрабатывает нажатие кнопки Принять предложение(принять обмен)."""

    model = ExchangeProposal

    def post(self, request, *args, **kwargs):
        proposal = self.get_object()
        proposal.status = "Подтвержден"
        proposal.save()

        return HttpResponseRedirect(reverse("ads:offers-exchanges"))


class RefuseExchangeProposalView(LoginRequiredMixin, SingleObjectMixin, View):
    """Обрабатывает нажатие кнопки Отказаться(отказаться от обмена)."""

    model = ExchangeProposal

    def post(self, request, *args, **kwargs):
        proposal = self.get_object()
        proposal.status = "Отклонен"
        proposal.save()

        return HttpResponseRedirect(reverse("ads:offers-exchanges"))


class ExchangeProposalDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление предложения об обмене."""

    model = ExchangeProposal
    success_url = reverse_lazy("ads:my-exchanges-list")


class AdSearchListView(ListView):
    """Поиск по объявлениям с пагинацией(ищет в названии и описании)."""

    model = Ad
    template_name = "ads_search.html"
    context_object_name = "ads"
    paginate_by = 20

    def get_queryset(self):
        """Полнотекстовый поиск, фильтрация по категории и состоянию товара."""

        query = self.request.GET.get("query", "")
        category = self.request.GET.get("category", "")
        condition = self.request.GET.get("condition", "")

        if self.request.user.is_authenticated:
            queryset = Ad.objects.exclude(user=self.request.user)
        else:
            queryset = Ad.objects.all()

        if query:
            queryset = queryset.annotate(search=SearchVector("title", "description")).filter(search=SearchQuery(query))

        if category:

ads/templates/ad.html
{% extends 'base.html' %}
{% load my_tags %}
{% block title %}{{ current_page }}{% endblock %}
{% block content %}
<div class="col-12">
    <div class="row">
<div class="col-1"></div>
    <div class="col-4">
<img src="{{ ad.image_url|media_filter }}" class="img-top mt-5" alt="...">
    </div>
        <div class="col-6">
<h1 class="mt-5">{{ ad.title }}</h1>
            <p style="font-size: 25px;">{{ ad.description }}</p>
            <p style="font-size: 25px;"><strong>Категория:</strong> {{ ad.category }}</p>
            <p style="font-size: 25px;"><strong>Состояние товара:</strong> {{ ad.condition }}</p>
            <p style="font-size: 25px;"><strong>Дата размещения:</strong> {{ ad.created_at|date:"d M Y" }}</p>
        </div>
        <div class="container-button mt-5">
            {% if my != 'Мое объявление' %}
                <a href="{% url 'ads:exchange-create' ad.pk %}"><button type="button" class="btn btn-secondary btn-lg" style="width: 250px;">Предложить обмен</button></a>
            {% endif %}
            <a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-danger btn-lg" style="width: 250px;">Назад</button></a>
                    </div>
        </div>
</div>
{% endblock %}

ads/templates/ad_form.html
{% extends 'base.html' %}
{% load my_tags %}
{% block title %}Форма объявления{% endblock %}
{% block content %}
<div class="container">
<form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset>
                <legend class="center">
                    {% if object %}
                    <h3>Редактирование объявления</h3>
                    {% else %}
                    <h3>Заполните форму для добавления объявления</h3>
                    {% endif %}
                </legend>
                <div class="container">
                {{ form.as_p }}
                {% if object %}
                <button type="submit" class="btn btn-secondary btn-lg">Редактировать</button>
                {% else %}
                <button type="submit" class="btn btn-secondary btn-lg">Создать</button>
                {% endif %}
                <a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-danger btn-lg">Назад</button></a>
                    </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

ads/templates/ads.html
{% extends 'base.html' %}
{% load my_tags %}
{% block title %}{{ current_page }}{% endblock %}
{% block content %}
<h1 class="mb-5 mt-3" style="text-align: center;">{{ current_page }}</h1>
<div class="container cards-container">
    {% for ad in ads %}
<div class="card" style="width: 18rem;">
    <a href="{% url 'ads:ad-detail' ad.pk %}"><img src="{{ ad.image_url|media_filter }}" class="card-img-top img-podsvetka" alt="..."></a>
  <div class="card-body">
    <h5 class="card-title">{{ ad.title }}</h5>
    <p class="card-text">{{ ad.description }}</p>
      {% if request.user == ad.user %}
    <a href="{% url 'ads:ad-update' ad.pk %}" class="btn btn-secondary" style="width: 100%;">Редактировать</a>
      <a href="{% url 'ads:ad-delete' ad.pk %}" class="btn btn-danger mt-2" style="width: 100%;">Удалить</a>
      {% else %}
    <a href="{% url 'ads:ad-detail' ad.pk %}" class="btn btn-primary" style="width: 100%;">Посмотреть объявление</a>
      <a href="{% url 'ads:exchange-create' ad.pk %}" class="btn btn-primary mt-2" style="width: 100%;">Предложить обмен</a>
      {% endif %}
  </div>
</div>
    {% endfor %}
    </div>
{% endblock %}

ads/templates/ads_search.html
{% extends 'base.html' %}
{% load my_tags %}
{% block title %}{{ current_page }}{% endblock %}
{% block content %}
<h1 class="mb-5 mt-3" style="text-align: center;">Результаты поиска</h1>

<div class="container mb-5">
<form method="get">
    <input type="text" name="query" placeholder="Поиск" value="{{ request.GET.query }}">
    <button class="btn btn-secondary" type="submit">Искать</button>
</form>
<form method="get">
        <select name="category">
            <option value="" selected>Любая категория</option>
            {% for choice in categories %}
            <option value="{{ choice.0 }}" {% if choice.0 == request.GET.category %}selected{% endif %}>{{ choice.1 }}</option>
            {% endfor %}
        </select>

        <select name="condition">
            <option value="" selected>Любое состояние</option>
            {% for choice in conditions %}
            <option value="{{ choice.0 }}" {% if choice.0 == request.GET.condition %}selected{% endif %}>{{ choice.1 }}</option>
            {% endfor %}
        </select>

        <button class="btn btn-secondary" type="submit">Фильтровать</button>
    </form>
</div>

{% if ads %}
<div class="container cards-container">
        {% for ad in ads %}
        <div class="card" style="width: 18rem;">
    <a href="{% url 'ads:ad-detail' ad.pk %}"><img src="{{ ad.image_url|media_filter }}" class="card-img-top img-podsvetka" alt="..."></a>
  <div class="card-body">
    <h5 class="card-title">{{ ad.title }}</h5>
    <p class="card-text">{{ ad.description }}</p>
      {% if request.user == ad.user %}
    <a href="{% url 'ads:ad-update' ad.pk %}" class="btn btn-secondary" style="width: 100%;">Редактировать</a>
      <a href="{% url 'ads:ad-delete' ad.pk %}" class="btn btn-danger mt-2" style="width: 100%;">Удалить</a>
      {% else %}
    <a href="{% url 'ads:ad-detail' ad.pk %}" class="btn btn-primary" style="width: 100%;">Посмотреть объявление</a>
      <a href="{% url 'ads:exchange-create' ad.pk %}" class="btn btn-primary mt-2" style="width: 100%;">Предложить обмен</a>
      {% endif %}
  </div>
</div>
        {% endfor %}
    {% include 'includes/pagination.html' %}
</div>
{% else %}
<div class="container">
    <p>Объявлений не найдено.</p>
{% endif %}
    </div>
{% endblock %}

ads/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Главная{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-qxo3VzuC+fSh18nvcLo7LZz6iwBcZKXz7ZV/KpXVRloG/kp/xsPfa/FAop2EKORRk" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style>
      </style>
</head>
<body>
{% include 'includes/navbar.html' %}
{% block content %}
{% endblock %}
{% include 'includes/footer.html' %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script defer src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-qxo3VzuC+fSh18nvcLo7LZz6iwBcZKXz7ZV/KpXVRloG/kp/xsPfa/FAop2EKORRk" crossorigin="anonymous"></script>
</body>
</html>

ads/templates/confirm-delete.html
{% extends 'base.html' %}
{% load my_tags %}
{% block title %}Подтверждение удаления{% endblock %}
{% block content %}
<div class="container">
<form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset>
                <div class="container" style="text-align: center;">
                    <h3 class="mt-3" style="font-size: 35px;">Вы действительно хотите удалить объявление?</h3>
                    <h4 class="mt-5" style="font-size: 30px;">{{ ad.title }}</h4>
                    <p style="font-size: 25px;">{{ ad.description|truncatechars:100 }}</p>
                <button type="submit" class="btn btn-danger btn-lg mt-5">Удалить</button>
                <a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-secondary btn-lg mt-5">Назад</button></a>
                    </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

ads/templates/exchange_proposal_form.html
{% extends 'base.html' %}
{% load my_tags %}
{% block title %}{{ current_page }}{% endblock %}
{% block content %}
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="col-12">
    <div class="row">
<div class="col-1"></div>
    <div class="col-4">
<img src="{{ ad.image_url|media_filter }}" class="img-top mt-5" alt="...">
    </div>
        <div class="col-6">
<h1 class="mt-5">{{ ad.title }}</h1>
            <p style="font-size: 25px;">{{ ad.description|truncatechars:100 }}</p>
            <p style="font-size: 25px;"><strong>Категория:</strong> {{ ad.category }}</p>
            <p style="font-size: 25px;"><strong>Состояние товара:</strong> {{ ad.condition }}</p>
            <p style="font-size: 25px;"><strong>Дата размещения:</strong> {{ ad.created_at|date:"d M Y" }}</p>
        </div>
        </div>
</div>
            </div>


            <div class="col-6">
                <div class="col-12">
    <div class="row">
<div class="col-1"></div>
    <form method="post">
        {% csrf_token %}
        <h3>Предлагаю взамен:</h3>
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Предложить обмен</button>
    </form>
        </div>
</div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

ads/templates/exchange_proposals1.html
{% extends 'base.html' %}
{% load my_tags %}
{% block title %}{{ current_page }}{% endblock %}
{% block content %}
{% load static %}

<div class="container">
    <div class="col-12">
        <h1 class="mb-5 mt-3" style="text-align: center;">{{ current_page }}</h1>

        {% for exchange in exchanges %}
        <div class="row">
            <div class="col-5">
                <div class="col-12">
    <div class="row">
<div class="col-1"></div>
    <div class="col-4">
<img src="{{ exchange.ad_receiver.image_url|media_filter }}" class="img-top mt-5" alt="...">
    </div>
        <div class="col-6">
<h1 class="mt-5">{{ exchange.ad_receiver.title }}</h1>
            <p style="font-size: 15px;"><strong>Категория:</strong> {{ exchange.ad_receiver.category }}</p>
            <p style="font-size: 15px;"><strong>Состояние товара:</strong> {{ exchange.ad_receiver.condition }}</p>
            <p style="font-size: 15px;"><strong>Статус:</strong> {{ exchange.status }}</p>
        </div>
        </div>
</div>
            </div>
            <div class="col-2">
<img src="{% static 'images/стрелка.jpg' %}" class="img-top mt-5" alt="...">
            </div>
<div class="col-5">
                <div class="col-12">
    <div class="row">
<div class="col-1"></div>
    <div class="col-4">
<img src="{{ exchange.ad_sender.image_url|media_filter }}" class="img-top mt-5" alt="...">
    </div>
        <div class="col-6">
<h1 class="mt-5">{{ exchange.ad_sender.title }}</h1>
            <p style="font-size: 15px;"><strong>Категория:</strong> {{ exchange.ad_sender.category }}</p>
            <p style="font-size: 15px;"><strong>Состояние товара:</strong> {{ exchange.ad_sender.condition }}</p>
            <p style="font-size: 15px;"><strong>Статус:</strong> {{ exchange.status }}</p>
        </div>
        </div>
</div>
            </div>
            {% if current_page == 'Вам предлагают обмен' %}
            <form method="post" action="{% url 'ads:accept-exchange-proposal' exchange.pk %}">{% csrf_token %}
            <button type="submit" class="btn btn-secondary btn-lg" style="width: 100%;">Принять предложение</button>
                </form>
            <form method="post" action="{% url 'ads:refuse-exchange-proposal' exchange.pk %}">{% csrf_token %}
                <button type="submit" class="btn btn-danger btn-lg" style="width: 100%;">Отказаться</button>
                </form>
            {% else %}
            <form method="post" action="{% url 'ads:delete-exchange-proposal' exchange.pk %}">{% csrf_token %}
            <button type="submit" class="btn btn-danger btn-lg" style="width: 100%;">Отменить</button>
                </form>
            {% endif %}
    </div>
        {% endfor %}
</div>
</div>
            {% endblock %}

ads/templates/home.html
{% extends 'base.html' %}
{% load my_tags %}
{% block title %}Главная{% endblock %}
{% load static %}
{% block content %}
<div class="container">
    <h1 class="mb-5 mt-3" style="text-align: center;">Добро пожаловать на сайт обмена вещами!</h1>
    <p class="mb-5 mt-3" style="text-align: center; font-size: 25px;">Отдай ненужную вещь, получи нужную!</p>

    <div class="container mb-5 container-button">
<form method="get" action="{% url 'ads:search-ads' %}">
    <input type="text" name="query" placeholder="Поиск" value="{{ request.GET.query }}">
    <button class="btn btn-secondary" type="submit">Искать</button>
</form>

</div>
</div>
{% endblock %}