ads/urls.py
from django.urls import path

from ads.apps import AdsConfig
from ads.views import (AcceptExchangeProposalView, AdCreateView, AdDeleteView, AdDetailView, AdListView, AdMyListView,
                       AdSearchListView, AdUpdateView, ExchangeProposalCreate, ExchangeProposalDeleteView,
                       ExchangeProposalListView, HomeTemplateView, MyExchangeProposalListView,
                       OffersExchangeProposalListView, RefuseExchangeProposalView)

app_name = AdsConfig.name

urlpatterns = [
    path("", HomeTemplateView.as_view(), name="home"),
    path("ad-create/", AdCreateView.as_view(), name="ad-create"),
    path("ads/", AdListView.as_view(), name="ads-list"),
    path("my_ads/", AdMyListView.as_view(), name="ads-mylist"),
    path("<int:pk>/ad/", AdDetailView.as_view(), name="ad-detail"),
    path("<int:pk>/update/", AdUpdateView.as_view(), name="ad-update"),
    path("<int:pk>/delete/", AdDeleteView.as_view(), name="ad-delete"),
    path("exchange-create/<int:pk>/", ExchangeProposalCreate.as_view(), name="exchange-create"),
    path("exchanges/", ExchangeProposalListView.as_view(), name="exchanges-list"),
    path("my_exchanges/", MyExchangeProposalListView.as_view(), name="my-exchanges-list"),
    path("offers_exchanges/", OffersExchangeProposalListView.as_view(), name="offers-exchanges"),
    path("accept-exchange-proposal/<int:pk>/", AcceptExchangeProposalView.as_view(), name="accept-exchange-proposal"),
    path("refuse-exchange-proposal/<int:pk>/", RefuseExchangeProposalView.as_view(), name="refuse-exchange-proposal"),
    path("delete-exchange-proposal/<int:pk>/", ExchangeProposalDeleteView.as_view(), name="delete-exchange-proposal"),
    path("search/", AdSearchListView.as_view(), name="search-ads"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ads.urls", namespace="ads")),
    path("", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import PersonalAccountDetailView, UserCreateView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="users:login"), name="logout"),
    path("user/<int:pk>/update/", UserUpdateView.as_view(), name="user-update"),
    path("personal-account/<int:pk>/", PersonalAccountDetailView.as_view(), name="personal-account"),
]

ads/models.py
from django.db import models

from users.models import User


class Ad(models.Model):
    """Модель объявления."""

    # выбор состояния товара
    CONDITION_CHOICES = (
        ("новый", "Новый"),
        ("б/у", "Б/у"),
    )
    # выбор категории
    CATEGORY_CHOICES = (
        ("одежда", "Одежда"),
        ("обувь", "Обувь"),
        ("аксессуары", "Аксессуары"),
        ("хобби", "Хобби"),
        ("электроника", "Электроника"),
        ("для дома и дачи", "Для дома и дачи"),
        ("запчасти", "Запчасти"),
        ("товары для детей", "Товары для детей"),
        ("красота и здоровье", "Красота и здоровье"),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Создатель объявления")
    title = models.CharField(max_length=250, verbose_name="Заголовок объявления")
    description = models.TextField(verbose_name="Описание товара")
    image_url = models.ImageField(upload_to="ad_images", verbose_name="Изображение", blank=True, null=True)
    category = models.CharField(max_length=30, verbose_name="Категория товара", choices=CATEGORY_CHOICES)
    condition = models.CharField(max_length=10, verbose_name="Состояние товара", choices=CONDITION_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания объявления")

    class Meta:
        verbose_name = "Объявление"
        verbose_name_plural = "Объявления"

    def __str__(self):
        return self.title


class ExchangeProposal(models.Model):
    """Модель для предложений обмена."""

    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name="Создатель предложения обмена")
    ad_sender = models.ForeignKey(
        Ad, on_delete=models.DO_NOTHING, verbose_name="Что менять", related_name="sender_exchange_proposals"
    )
    ad_receiver = models.ForeignKey(
        Ad, on_delete=models.DO_NOTHING, verbose_name="На что менять", related_name="receiver_exchange_proposals"
    )
    comment = models.TextField(verbose_name="Комментарий")
    status = models.CharField(max_length=15, verbose_name="Статус", default="Ожидает")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания объявления")

    class Meta:
        verbose_name = "Предложение обмена"
        verbose_name_plural = "Предложения обмена"

ads/forms.py
from django import forms

from .mixins import StyleFormMixin
from .models import Ad, ExchangeProposal


class AdForm(StyleFormMixin, forms.ModelForm):
    """Форма для объявления."""

    class Meta:
        model = Ad
        fields = ["title", "description", "image_url", "category", "condition"]
        # widgets = {
        #     'condition': forms.Select(attrs={'class': 'form-control'}),
        # }


class ExchangeProposalForm(StyleFormMixin, forms.ModelForm):
    """Форма для обмена."""

    class Meta:
        model = ExchangeProposal
        fields = [
            "ad_receiver",
            "comment",
        ]

    def __init__(self, *args, **kwargs):

        # Устанавливаем queryset, чтобы выбрать только объявления текущего пользователя
        user = kwargs.pop("user", None)  # Получаем пользователя из kwargs и удаляем его оттуда
        super().__init__(*args, **kwargs)

        if user:
            self.fields["ad_receiver"].queryset = Ad.objects.filter(user=user)
        else:
            self.fields["ad_receiver"].queryset = Ad.objects.none()
        self.fields["comment"].initial = ""

ads/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.postgres.search import SearchQuery, SearchVector
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView
from django.views.generic.detail import SingleObjectMixin

from ads.forms import AdForm, ExchangeProposalForm
from ads.models import Ad, ExchangeProposal


class HomeTemplateView(TemplateView):
    """Главная страница."""

    template_name = "home.html"

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Главная"

        return context


class AdCreateView(LoginRequiredMixin, CreateView):
    """Создание объявления."""

    model = Ad
    form_class = AdForm
    template_name = "ad_form.html"

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Добавление объявления"

        return context

    def form_valid(self, form):
        """Добавляет текущего пользователя, как создателя объявления."""

        ad = form.save(commit=False)
        ad.user = self.request.user
        ad.save()

        return super().form_valid(form)

    def get_success_url(self):
        """Перенаправление на созданное объявление."""

        return reverse("ads:ad-detail", kwargs={"pk": self.object.pk})


class AdListView(ListView):
    """Список объявлений."""

    model = Ad
    template_name = "ads.html"
    context_object_name = "ads"

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Объявления"

        return context

    def get_queryset(self):
        """Возвращает объявления других пользователей."""

        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            queryset = queryset.exclude(user=user)

        return queryset


class AdMyListView(LoginRequiredMixin, ListView):
    """Список моих объявлений."""

    model = Ad
    template_name = "ads.html"
    context_object_name = "ads"

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Мои объявления"

        return context

    def get_queryset(self):
        """Возвращает объявления текущего пользователя."""

        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            queryset = queryset.filter(user=user)
        else:
            queryset = Ad.objects.none()

        return queryset


class AdDetailView(DetailView):
    """Информация об объявлении."""

    model = Ad
    template_name = "ad.html"
    context_object_name = "ad"

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        if Ad.objects.get(id=self.object.id).user == self.request.user:
            my = 'Мое объявление'
        else:
            my = ''
        context["current_page"] = "Объявление"
        context["my"] = my

        return context


class AdUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование объявления."""

    model = Ad
    form_class = AdForm
    template_name = "ad_form.html"
    success_url = reverse_lazy("ads:ads-mylist")

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Редактирование"

        return context


class AdDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление объявления."""

    model = Ad
    template_name = "confirm-delete.html"
    success_url = reverse_lazy("ads:ads-mylist")

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Удаление объявления"

        return context


class ExchangeProposalCreate(LoginRequiredMixin, CreateView):
    """Создание обмена."""

    model = ExchangeProposal
    form_class = ExchangeProposalForm
    template_name = "exchange_proposal_form.html"
    success_url = reverse_lazy("ads:ads-list")

    def get_form_kwargs(self):
        """Передаем текущего пользователя в форму."""

        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})

        return kwargs

    def form_valid(self, form):
        """Автоматически устанавливаем объявление отправителя и делаем владельцем текущего пользователя."""

        user = self.request.user
        ad_id = self.kwargs.get("pk")
        sender_ad = Ad.objects.get(id=ad_id)
        form.instance.ad_sender = sender_ad
        form.instance.owner = user

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        ad_id = self.kwargs.get("pk")
        context["current_page"] = "Предложение обмена"
        context["ad"] = Ad.objects.get(id=ad_id)

        return context


class ExchangeProposalListView(LoginRequiredMixin, ListView):
    """Список обменов."""

    model = ExchangeProposal
    template_name = "exchange_proposals.html"
    context_object_name = "exchanges_ok"

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон и списков состоявшихся и не состоявшихся обменов."""

        context = super().get_context_data(**kwargs)
        user = self.request.user
        users_ads = Ad.objects.filter(user=user)
        context["current_page"] = "Обмены"
        # принятые обмены
        context["exchanges_ok"] = ExchangeProposal.objects.filter(
            Q(ad_sender__in=users_ads) | Q(ad_receiver__in=users_ads), status="Подтвержден"
        )
        # отклоненные обмены
        context["exchanges"] = ExchangeProposal.objects.filter(
            Q(ad_sender__in=users_ads) | Q(ad_receiver__in=users_ads), status="Отклонен"
        )

        return context


class MyExchangeProposalListView(LoginRequiredMixin, ListView):
    """Я предлагаю поменяться."""

    model = ExchangeProposal
    template_name = "exchange_proposals1.html"
    context_object_name = "exchanges"

    def get_queryset(self):
        """Возвращает предложения обмена созданные текущим пользователем."""

        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            queryset = queryset.filter(owner=user, status="Ожидает")
        else:
            queryset = Ad.objects.none()

        return queryset

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Вы предлагаете обмен"

        return context


class OffersExchangeProposalListView(LoginRequiredMixin, ListView):
    """Вам предлагают поменяться."""

    model = ExchangeProposal
    template_name = "exchange_proposals1.html"
    context_object_name = "exchanges"

    def get_queryset(self):
        """Возвращает предложения обмена от других пользователей."""

        queryset = super().get_queryset()
        user = self.request.user
        users_ads = Ad.objects.exclude(user=user)
        queryset = ExchangeProposal.objects.filter(ad_receiver__in=users_ads, status="Ожидает")

        return queryset

    def get_context_data(self, **kwargs):
        """Передача названия текущей страницы в шаблон."""

        context = super().get_context_data(**kwargs)
        context["current_page"] = "Вам предлагают обмен"

        return context


class AcceptExchangeProposalView(LoginRequiredMixin, SingleObjectMixin, View):
    """Обрабатывает нажатие кнопки Принять предложение(принять обмен)."""

    model = ExchangeProposal

    def post(self, request, *args, **kwargs):
        proposal = self.get_object()
        proposal.status = "Подтвержден"
        proposal.save()

        return HttpResponseRedirect(reverse("ads:offers-exchanges"))


class RefuseExchangeProposalView(LoginRequiredMixin, SingleObjectMixin, View):
    """Обрабатывает нажатие кнопки Отказаться(отказаться от обмена)."""

    model = ExchangeProposal

    def post(self, request, *args, **kwargs):
        proposal = self.get_object()
        proposal.status = "Отклонен"
        proposal.save()

        return HttpResponseRedirect(reverse("ads:offers-exchanges"))


class ExchangeProposalDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление предложения об обмене."""

    model = ExchangeProposal
    success_url = reverse_lazy("ads:my-exchanges-list")


class AdSearchListView(ListView):
    """Поиск по объявлениям с пагинацией(ищет в названии и описании)."""

    model = Ad
    template_name = "ads_search.html"
    context_object_name = "ads"
    paginate_by = 20

    def get_queryset(self):
        """Полнотекстовый поиск, фильтрация по категории и состоянию товара."""

        query = self.request.GET.get("query", "")
        category = self.request.GET.get("category", "")
        condition = self.request.GET.get("condition", "")

        if self.request.user.is_authenticated:
            queryset = Ad.objects.exclude(user=self.request.user)
        else:
            queryset = Ad.objects.all()

        if query:
            queryset = queryset.annotate(search=SearchVector("title", "description")).filter(search=SearchQuery(query))

        if category:

ads/templates/includes/footer.html
<footer class="footer mt-auto py-3 bg-body-tertiary">
  <div class="container">
    <span class="text-body-secondary">&copy; 2024 Sharing Things</span>
  </div>
</footer>

ads/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Ninth navbar example">
    <div class="container-xl">
      <a class="navbar-brand" href="#">{{ current_page }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07XL" aria-controls="navbarsExample07XL" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample07XL">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'ads:home' %}">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ads:ads-list' %}">Объявления</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ads:ads-mylist' %}">Мои объявления</a>
          </li>
          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Мои обмены</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'ads:offers-exchanges' %}">Вам предлагают обмен</a></li>
              <li><a class="dropdown-item" href="{% url 'ads:my-exchanges-list' %}">Вы предлагаете обмен</a></li>
              <li><a class="dropdown-item" href="{% url 'ads:exchanges-list' %}">Обмены</a></li>
            </ul>
          </li>
          {% endif %}

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Действия</a>
            <ul class="dropdown-menu">
              {% if not user.is_authenticated %}
              <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
              <li><a class="dropdown-item" href="{% url 'users:register' %}">Зарегистрироваться</a></li>
              {% endif %}
              {% if user.is_authenticated %}
              <li><a class="dropdown-item" href="{% url 'users:personal-account' user.pk %}">Личный кабинет</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'ads:ad-create' %}">Добавить объявление</a></li>
              {% if user.is_authenticated %}
              <li><form method="post" action="{% url 'users:logout' %}">
            {% csrf_token %}
                <a><button type="submit" class="btn">Выход</button></a>
              </form></li>
              {% endif %}
            </ul>
          </li>
        </ul>
        <form method="get" action="{% url 'ads:search-ads' %}">
    <input type="text" name="query" placeholder="Введите поисковый запрос" value="{{ request.GET.query }}">
    <button class="btn btn-secondary" type="submit">Искать</button>
</form>
      </div>
    </div>
  </nav>

ads/templates/includes/pagination.html
<div class="container">
<nav aria-label="Page navigation">
  <ul class="pagination pagination-lg">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link textp podsvetkav" href="?page={{ page_obj.previous_page_number }}">Назад</a>
    </li>
    {% endif %}
      {% for p in page_obj.paginator.page_range %}
        {% if p == page_obj.number %}
          <li class="page-item"><a class="page-link paginat" href="">{{ p }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link textp podsvetkav" href="?page={{ p }}">{{ p }}</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link textp podsvetkav" href="?page={{ page_obj.next_page_number }}">Вперед</a>
    </li>
    {% endif %}
  </ul>
</nav>
    </div>